"""Content points of /proto/: assets/topdown/content_points.json -> static DOM.

    python tools/build_proto_content.py                 # write the region in proto/index.html
    python tools/build_proto_content.py --check         # fail if it is stale or the source is invalid
    python tools/build_proto_content.py --copy-md <f>   # copy review table (id, EN, RU, source)

Every word of a content card is in proto/index.html before any script runs:
the <article>s are written here from the JSON, between two marker comments.
Runtime JS (proto/main.js) only activates them — it never creates or removes
text. That is what a crawler, a screen reader and a future static fallback
read; the canvas is not the only source of information.

The copy is not authored in the JSON either. Each title/body is quoted from
the site's own copy (tools/build_site.py FEATURES, kicker = tools/biomes.py
biome name) and this tool fails if a quote drifts from its source — no
invented claims, no hand-maintained duplicate.

Both locales are in the page: EN visible, RU in a `hidden` section; /proto/
switches with ?lang=ru (deterministic, no detection). A future per-locale route
can stamp one locale per page from the same JSON.
"""

import argparse
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

SRC = ROOT / "assets" / "topdown" / "content_points.json"
PAGE = ROOT / "proto" / "index.html"
RUNTIME = ROOT / "assets" / "topdown" / "layout.runtime.json"
BEGIN = "<!-- content-points:begin — generated by tools/build_proto_content.py from assets/topdown/content_points.json; do not edit -->"
END = "<!-- content-points:end -->"
BIOME_ORDER = ["village", "forest", "mine", "spirit", "home"]
SIDES = ("left", "right", "auto")
PLACEHOLDER = re.compile(r"\b(UNKNOWN|TODO|TBD|lorem|placeholder)\b", re.I)
H1 = {"en": "Fellmise — journey through the world", "ru": "Fellmise — путь через мир"}


def load(path=SRC):
    return json.loads(path.read_text(encoding="utf-8"))


def objects(runtime):
    """id -> (biome index, object) for every sprite and board of the runtime layout."""
    out = {}
    for bi, b in enumerate(runtime["biomes"].values()):
        for o in b["sprites"] + b.get("boards", []):
            out[o["id"]] = (bi, o)
    return out


def anchor_z(runtime, oid):
    bi, o = objects(runtime)[oid]
    return -bi * runtime["biome_spacing"] + o["pos"][2]


def check(data, runtime=None):
    """Problems with the content source, [] if none."""
    from build_site import FEATURES
    from biomes import BIOMES
    feats = {f["id"]: f for f in FEATURES}
    names = {b["id"]: b for b in BIOMES}
    runtime = runtime or json.loads(RUNTIME.read_text(encoding="utf-8"))
    objs = objects(runtime)
    bad = []
    pts = data.get("points", [])
    locales = data.get("locales", [])
    if locales != ["en", "ru"]:
        bad.append(f"locales: {locales} (нужно ['en', 'ru'])")
    ids = [p.get("id") for p in pts]
    if len(ids) != len(set(ids)):
        bad.append("повторяющиеся id")
    for p in pts:
        pid = p.get("id", "?")
        if not re.fullmatch(r"[a-z]+-[a-z-]+", pid or ""):
            bad.append(f"{pid}: id не стабильного вида (biome-subject)")
        if p.get("biome") not in BIOME_ORDER:
            bad.append(f"{pid}: неизвестный biome {p.get('biome')}")
        if p.get("side") not in SIDES:
            bad.append(f"{pid}: side {p.get('side')}")
        a = p.get("activation", {})
        if not (isinstance(a.get("core"), (int, float)) and isinstance(a.get("range"), (int, float))
                and 0 < a["core"] < a["range"] <= 60):
            bad.append(f"{pid}: activation {a} (нужно 0 < core < range <= 60)")
        oid = p.get("anchor", {}).get("object")
        if oid not in objs:
            bad.append(f"{pid}: anchor {oid} нет в layout.runtime.json")
        elif objs[oid][1].get("visible") is False:
            bad.append(f"{pid}: anchor {oid} скрыт в layout")
        elif list(runtime["biomes"])[objs[oid][0]] != p.get("biome"):
            bad.append(f"{pid}: anchor {oid} стоит не в биоме {p.get('biome')}")
        if p.get("marker", {}).get("object") not in objs:
            bad.append(f"{pid}: marker {p.get('marker')} не найден")
        src = p.get("copy_source", {})
        f = feats.get(src.get("features_id"))
        if src.get("file") != "tools/build_site.py" or f is None:
            bad.append(f"{pid}: copy_source {src} не указывает на build_site.FEATURES")
            continue
        for loc in ("en", "ru"):
            c = p.get(loc, {})
            for k in ("kicker", "title", "body"):
                v = c.get(k)
                if not isinstance(v, str) or not v.strip():
                    bad.append(f"{pid}.{loc}.{k}: пусто")
                elif PLACEHOLDER.search(v):
                    bad.append(f"{pid}.{loc}.{k}: плейсхолдер в публикуемом тексте")
            # verbatim quote of the site's own copy
            if c.get("title") != f[f"{loc}_t"]:
                bad.append(f"{pid}.{loc}.title расходится с build_site.FEATURES[{f['id']}]")
            if c.get("body") != f[f"{loc}_p"]:
                bad.append(f"{pid}.{loc}.body расходится с build_site.FEATURES[{f['id']}]")
            if c.get("kicker") != names[p["biome"]][loc]:
                bad.append(f"{pid}.{loc}.kicker расходится с biomes.BIOMES[{p['biome']}]")
    if [p.get("biome") for p in sorted(pts, key=lambda p: p.get("order", 0))] != BIOME_ORDER:
        bad.append("нужно ровно 5 точек, по одной на биом, в порядке маршрута")
    if not bad:
        # along the route (z decreasing): windows must not overlap, so at most
        # one card is ever on screen
        zs = sorted(((anchor_z(runtime, p["anchor"]["object"]), p) for p in pts), key=lambda t: -t[0])
        if [p["id"] for _, p in zs] != [p["id"] for p in sorted(pts, key=lambda p: p["order"])]:
            bad.append("order не совпадает с порядком якорей по маршруту")
        for (z1, p1), (z2, p2) in zip(zs, zs[1:]):
            if (z1 - p1["activation"]["range"]) <= (z2 + p2["activation"]["range"]):
                bad.append(f"окна {p1['id']} и {p2['id']} перекрываются")
    return bad


def region(data):
    esc = lambda s: html.escape(s, quote=False)
    att = lambda s: html.escape(str(s), quote=True)
    pts = sorted(data["points"], key=lambda p: p["order"])
    out = [BEGIN, '<div id="content-overlay">']
    for loc in data["locales"]:
        hidden = "" if loc == data["default_locale"] else " hidden"
        out.append(f'  <section class="content-locale" lang="{loc}" data-locale="{loc}"{hidden}>')
        out.append(f'    <h1 class="content-visually-hidden">{esc(H1[loc])}</h1>')
        for p in pts:
            c = p[loc]
            hid = f"cp-{loc}-{p['id']}"
            out.append(
                f'    <article class="content-point" id="{hid}" data-id="{att(p["id"])}" data-order="{p["order"]}"'
                f' data-biome="{att(p["biome"])}" data-anchor="{att(p["anchor"]["object"])}"'
                f' data-marker="{att(p["marker"]["object"])}" data-side="{att(p["side"])}"'
                f' data-core="{p["activation"]["core"]}" data-range="{p["activation"]["range"]}"'
                f' aria-labelledby="{hid}-title">')
            out.append(f'      <p class="content-point__kicker">{esc(c["kicker"])}</p>')
            out.append(f'      <h2 class="content-point__title" id="{hid}-title">{esc(c["title"])}</h2>')
            out.append(f'      <p class="content-point__body">{esc(c["body"])}</p>')
            out.append('    </article>')
        out.append('  </section>')
    out.append('</div>')
    out.append(END)
    return "\n".join(out)


def render(page_text, data):
    if BEGIN not in page_text or END not in page_text:
        raise SystemExit("в proto/index.html нет маркеров content-points")
    a = page_text.index(BEGIN)
    b = page_text.index(END) + len(END)
    return page_text[:a] + region(data) + page_text[b:]


def copy_md(data):
    rows = ["| id | EN title | EN body | RU title | RU body | source |", "|---|---|---|---|---|---|"]
    for p in sorted(data["points"], key=lambda p: p["order"]):
        s = p["copy_source"]
        cell = lambda t: t.replace("|", "\\|")
        rows.append(f"| {p['id']} | {cell(p['en']['title'])} | {cell(p['en']['body'])} | "
                    f"{cell(p['ru']['title'])} | {cell(p['ru']['body'])} | "
                    f"{s['file']} FEATURES[{s['features_id']}]; kicker {s['kicker']}; {cell(s['why'])} |")
    return "\n".join(rows) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--copy-md")
    args = ap.parse_args()
    data = load()
    bad = check(data)
    if bad:
        print("content_points.json — ошибки:")
        for b in bad:
            print("  " + b)
        sys.exit(1)
    if args.copy_md:
        pathlib.Path(args.copy_md).write_text(copy_md(data), encoding="utf-8")
        print(f"-> {args.copy_md}")
        return
    have = PAGE.read_text(encoding="utf-8")
    want = render(have, data)
    if args.check:
        if have != want:
            print("УСТАРЕЛ: proto/index.html — запустите python tools/build_proto_content.py")
            sys.exit(1)
        print("актуален: proto/index.html (content points)")
        return
    PAGE.write_text(want, encoding="utf-8", newline="\n")
    print(f"-> proto/index.html ({len(data['points'])} точек × {len(data['locales'])} локали)")


if __name__ == "__main__":
    main()
