"""Key art of /proto/: assets/topdown/key_art.json.

    python tools/key_art.py            # check, (re)build WebPs, write proto/index.html, print timeline
    python tools/key_art.py --check    # fail on an invalid plan, stale WebP or stale HTML

A slot is a DOM illustration window over the world, anchored to a stable
layout object. Its window (peak ± range of camera z) must sit where the route
is free: no content card visible, no biome transition dim, a camera focus at
most at its tail (weight <= 0.05, frame ~40 m), and out before the ground
blend that leaves the slot's own biome starts.
Live slots: `master` (approved PNG) -> `src` (runtime WebP, derived here),
and a static <figure> per slot in proto/index.html between the key-art
markers (alt EN in the HTML, RU in data-alt-ru). main.js only activates them.
"""

import argparse
import html
import io
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import build_proto_content as BPC  # noqa: E402
import camera_choreography as CC   # noqa: E402

SRC = ROOT / "assets" / "topdown" / "key_art.json"
PAGE = ROOT / "proto" / "index.html"
BEGIN = "<!-- key-art:begin — generated by tools/key_art.py from assets/topdown/key_art.json; do not edit -->"
END = "<!-- key-art:end -->"
WEBP_Q = 90
VIEW = (1280, 800)
BIOMES = ["village", "forest", "mine", "spirit", "home"]


def load(path=SRC):
    return json.loads(path.read_text(encoding="utf-8"))


def peak(slot, rt):
    return CC.anchors(rt)[slot["anchor"]["object"]][2] + slot["anchor"].get("peak_offset", 0)


def exit_range(slot):
    a = slot["activation"]
    return a.get("exit_range", a["range"])


def window(slot, rt):
    """(z_end, z_start): where the slot is on screen at all (presence > 0).
    The far side (smaller z) may fade faster: activation.exit_core/exit_range."""
    p = peak(slot, rt)
    return p - exit_range(slot), p + slot["activation"]["range"]


def presence(slot, rt, z):
    """The runtime presence (proto/main.js keyArtWeight), for checks."""
    a, p = slot["activation"], peak(slot, rt)
    core, rng = (a["core"], a["range"]) if z >= p else (a.get("exit_core", a["core"]), exit_range(slot))
    d = abs(z - p)
    if d <= core:
        return 1.0
    if d >= rng:
        return 0.0
    u = (d - core) / (rng - core)
    return 1 - u * u * (3 - 2 * u)


def first_visible(obj_id, rt):
    """Camera z (route direction) where a world object's lowest opaque row
    first enters the top of a 1280x800 frame at the auto zoom."""
    from PIL import Image
    import numpy as np
    _, x, z, o = CC.anchors(rt)[obj_id]
    src = json.loads((ROOT / "proto" / "sprite_contact.json").read_text(encoding="utf-8"))["sprites"][o["t"]]["src"]
    with Image.open(ROOT / src) as im:
        al = np.asarray(im.convert("RGBA"))[..., 3] > 16
    rows = np.nonzero(al.any(1))[0]
    z_low = z - o["h"] / 2 + (rows.max() + 1) / al.shape[0] * o["h"]
    ch = CC.load()
    pk = CC.peaks(ch, rt)
    zc = z_low + 40
    while zc > z_low - 40:
        if zc - CC.frame_at(ch, rt, zc, pk)[0] / 2 < z_low:
            return zc
        zc -= 0.05
    return None


def aspect(slot):
    a, b = (int(x) for x in slot["aspect"].split(":"))
    return a / b


def display_px(slot):
    w = slot["display"]["width"]
    return w, round(w / aspect(slot))


FOCUS_MAX = 0.05       # camera focus weight a key art window may coexist with (frame ~40 m)


def focus_max(slot, rt):
    """Highest camera-focus weight anywhere the slot is on screen."""
    ch = CC.load()
    pk = CC.peaks(ch, rt)
    e, s = window(slot, rt)
    z, top = s, 0.0
    while z >= e:
        top = max(top, CC.frame_at(ch, rt, z, pk)[2])
        z -= 0.25
    return top


def busy(rt):
    """Route spans already taken: (z_start, z_end, what). Camera focus is
    checked by weight (focus_max), not by its window."""
    cp = BPC.load()
    out = []
    for p in cp["points"]:
        z = BPC.anchor_z(rt, p["anchor"]["object"])
        out.append((z + p["activation"]["range"], z - p["activation"]["range"], "content card " + p["id"]))
    for t in rt["presentation"]["transitions"]:
        hw = t["dim"]["half_width"]
        out.append((t["anchor_z"] + hw, t["anchor_z"] - hw, f"transition {t['from']}->{t['to']}"))
    return out


def check(data, rt=None):
    rt = rt or CC.runtime()
    bad = []
    slots = data.get("slots", [])
    a = CC.anchors(rt)
    if not 1 <= len(slots) <= 3:
        bad.append(f"слотов {len(slots)}: нужно 1..3")
    ids = [s.get("id") for s in slots]
    if len(ids) != len(set(ids)):
        bad.append("повторяющиеся id")
    for s in slots:
        sid = s.get("id", "?")
        if s.get("status") not in ("planned", "live"):
            bad.append(f"{sid}: status {s.get('status')} (planned или live)")
        if s.get("biome") not in BIOMES:
            bad.append(f"{sid}: biome {s.get('biome')}")
        obj = s.get("anchor", {}).get("object")
        if obj not in a:
            bad.append(f"{sid}: якоря {obj} нет в layout")
            continue
        if a[obj][0] != s.get("biome"):
            bad.append(f"{sid}: якорь не в биоме {s.get('biome')}")
        if s.get("side") not in ("left", "right"):
            bad.append(f"{sid}: side {s.get('side')}")
        act = s.get("activation", {})
        if not (isinstance(act.get("core"), (int, float)) and isinstance(act.get("range"), (int, float))
                and 0 < act["core"] < act["range"] <= 40):
            bad.append(f"{sid}: activation {act}")
        if ("exit_core" in act) != ("exit_range" in act) or (
                "exit_core" in act and not 0 < act["exit_core"] < act["exit_range"] <= 40):
            bad.append(f"{sid}: exit_core/exit_range {act}")
        if not re.fullmatch(r"\d+:\d+", str(s.get("aspect", ""))) or not 0.6 <= aspect(s) <= 2.0:
            bad.append(f"{sid}: aspect {s.get('aspect')}")
            continue
        w, h = display_px(s)
        if not (280 <= w <= 560 and h <= 0.6 * VIEW[1]):
            bad.append(f"{sid}: display {w}×{h} вне 280..560 px ширины / 60% высоты кадра")
        tw, th = s.get("target_px", [0, 0])
        if tw < 2 * w or th < 2 * h or abs(tw / th - aspect(s)) > 0.01:
            bad.append(f"{sid}: target_px {tw}×{th} меньше 2× display или не в {s['aspect']}")
        alt = s.get("alt", {})
        if s.get("status") == "planned" and (alt.get("en") or alt.get("ru")):
            bad.append(f"{sid}: alt написан до арта")
        if s.get("status") == "live":
            if not (alt.get("decorative") or (alt.get("en") and alt.get("ru"))):
                bad.append(f"{sid}: у live-слота нужен alt EN и RU (или decorative)")
            for k in ("master", "src"):
                if not s.get(k) or not (ROOT / s[k]).exists():
                    bad.append(f"{sid}: нет файла {k} {s.get(k)}")
            if s.get("master") and (ROOT / s["master"]).exists():
                from PIL import Image
                with Image.open(ROOT / s["master"]) as im:
                    if list(im.size) != list(s.get("target_px", [0, 0])):
                        bad.append(f"{sid}: master {im.size} не равен target_px {s.get('target_px')}")
        if s.get("supports", {}).get("content_point") not in {p["id"] for p in BPC.load()["points"]}:
            bad.append(f"{sid}: supports.content_point не найден")
    if bad:
        return bad
    end = CC.route_end(CC.load(), rt)
    wins = sorted(((window(s, rt), s) for s in slots), key=lambda t: -t[0][1])
    if [s["id"] for _, s in wins] != ids:
        bad.append("слоты не в порядке маршрута")
    for ((e1, _), s1), ((_, s2), t2) in zip(wins, wins[1:]):
        if s2 >= e1:
            bad.append(f"{s1['id']} и {t2['id']} перекрываются")
    for (e, s), slot in wins:
        if e < end:
            bad.append(f"{slot['id']}: окно заходит за конец маршрута")
        fm = focus_max(slot, rt)
        if fm > FOCUS_MAX:
            bad.append(f"{slot['id']}: на окне вес фокуса камеры до {fm:.2f} (> {FOCUS_MAX})")
        for t in rt["presentation"]["transitions"]:
            if t["from"] == slot["biome"] and e < t["blend_z"][0]:
                bad.append(f"{slot['id']}: окно заходит в смешение грунта {t['from']}→{t['to']} (с z {t['blend_z'][0]})")
        for bs, be, what in busy(rt):
            if e < bs and s > be:
                bad.append(f"{slot['id']}: окно {s:.0f}..{e:.0f} пересекается с «{what}» ({bs:.0f}..{be:.0f})")
        y = slot.get("yields_to")
        if y:
            if y.get("object") not in CC.anchors(rt):
                bad.append(f"{slot['id']}: yields_to {y} нет в layout")
            else:
                fv = first_visible(y["object"], rt)
                if fv is None or e < fv + y.get("gap_m", 0):
                    bad.append(f"{slot['id']}: окно гаснет на z {e:.2f}, а {y['object']} входит в кадр на "
                               f"{fv:.2f} — нужен зазор {y.get('gap_m', 0)} м")
    return bad


def webp_bytes(master):
    from PIL import Image
    with Image.open(master) as im:
        b = io.BytesIO()
        im.convert("RGB").save(b, "WEBP", quality=WEBP_Q, method=6)
    return b.getvalue()


def region(data):
    def att(v):
        return html.escape(str(v), quote=True)
    out = [BEGIN, '<div id="keyart-overlay">']
    for s in data["slots"]:
        if s.get("status") != "live":
            continue
        alt = s["alt"]
        en = "" if alt.get("decorative") else alt["en"]
        ru = "" if alt.get("decorative") else alt["ru"]
        out.append(
            f'  <figure class="key-art" data-id="{att(s["id"])}" data-biome="{att(s["biome"])}"'
            f' data-anchor="{att(s["anchor"]["object"])}" data-peak-offset="{s["anchor"].get("peak_offset", 0)}"'
            f' data-core="{s["activation"]["core"]}" data-range="{s["activation"]["range"]}"'
            + (f' data-exit-core="{s["activation"]["exit_core"]}" data-exit-range="{s["activation"]["exit_range"]}"'
               if "exit_range" in s["activation"] else "")
            + f' data-side="{att(s["side"])}" data-preload="{s["lazy"]["preload_ahead_m"]}"'
            f' data-supports="{att(s["supports"]["content_point"])}">')
        out.append(
            f'    <img data-src="../{att(s["src"])}" width="{s["target_px"][0]}" height="{s["target_px"][1]}"'
            f' alt="{att(en)}" data-alt-ru="{att(ru)}" decoding="async">')
        out.append('  </figure>')
    out.append('</div>')
    out.append(END)
    return "\n".join(out)


def render(page_text, data):
    if BEGIN not in page_text or END not in page_text:
        raise SystemExit("в proto/index.html нет маркеров key-art")
    a, b = page_text.index(BEGIN), page_text.index(END) + len(END)
    return page_text[:a] + region(data) + page_text[b:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    data, rt = load(), CC.runtime()
    stale = []
    for s in data["slots"]:
        if s.get("status") == "live" and (ROOT / s["master"]).exists():
            want = webp_bytes(ROOT / s["master"])
            have = (ROOT / s["src"]).read_bytes() if (ROOT / s["src"]).exists() else None
            if have != want:
                if args.check:
                    stale.append(s["src"])
                else:
                    (ROOT / s["src"]).write_bytes(want)
                    print(f"-> {s['src']} ({len(want) // 1024} KB)")
    page = PAGE.read_text(encoding="utf-8")
    new = render(page, data)
    if new != page:
        if args.check:
            stale.append("proto/index.html (key art)")
        else:
            PAGE.write_text(new, encoding="utf-8", newline="\n")
            print("-> proto/index.html (key art)")
    bad = check(data, rt) + [f"устарел {x} — запустите python tools/key_art.py" for x in stale]
    if bad:
        print("key_art.json — ошибки:")
        for b in bad:
            print("  " + b)
        sys.exit(1)
    if args.check:
        print("актуален: assets/topdown/key_art.json, WebP и proto/index.html (key art)")
        return
    for s in data["slots"]:
        e, st = window(s, rt)
        p = peak(s, rt)
        w, h = display_px(s)
        print(f"{s['id']:17} {s['biome']:8} enter {st:7.1f}  peak {p:7.1f} (±{s['activation']['core']})  "
              f"exit {e:7.1f}  {s['side']:5} {s['aspect']} {w}×{h} css  target {s['target_px'][0]}×{s['target_px'][1]}"
              f"  focus<= {focus_max(s, rt):.3f}")


if __name__ == "__main__":
    main()
